name: Lint

on: [push]

jobs:
  codespell:
    name: Spelling
    runs-on: ubuntu-latest
    steps:
        - name: Checkout sources
          uses: actions/checkout@v2

        - name: Run Codespell
          uses: codespell-project/actions-codespell@master
